server:
  port: 8081
spring:
  application:
    name: "ms-requests"
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/db_requests_ms"
    username: "dbeaver"
    password: 12345
    pool:
      enabled: true
  flyway:
    url: "jdbc:postgresql://localhost:5432/db_requests_ms"
    user: "dbeaver"
    password: 12345
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "db_requests_ms"
    schema: "public"
    username: "dbeaver"
    password: 12345
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080/api/v1/users"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
