server:
  port: 8081

spring:
  application:
    name: "ms-requests"
  r2dbc:
    url: "r2dbc:postgresql://db-requests:5432/db_requests_ms"
    username: "dbeaver"
    password: 12345
    pool:
      enabled: true
  flyway:
    url: "jdbc:postgresql://db-requests:5432/db_requests_ms"
    user: "dbeaver"
    password: 12345

# --- SECCIÓN DE ADAPTADORES CONSOLIDADA ---
adapters:
  r2dbc:
    host: "db-requests" #"localhost"
    port: 5432
    database: "db_requests_ms"
    schema: "public"
    username: "dbeaver"
    password: 12345
  restconsumer:
    timeout: 5000
    url: "http://ms-authentication:8080" #ms-authentication reemplaza a localhost

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true

security:
  jwt:
    secret: "${JWT_SECRET:EstaEsUnaClaveSecretaDeEjemploParaElRetoPragmaConMasDe256BitsDeLongitud}"

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"